[package]
name = "testing"
version = "0.0.1"
authors = ["Lukas Pustina <lukas.pustina@centerdevice.com>"]

edition = "2018"

[lib]
name = "testing"
path = "src/lib.rs"

[dependencies]
env_logger = "0.6.0"

